#ifndef _LCOM_UART_H
#define _LCOM_UART_H

#include <lcom/lcf.h>

#define COM1 0x3F8
#define COM1_IRQ 4

#define RBR 0x00 // Receiver Buffer Register: Register to read the characters received from the serial line
#define THR 0x00 // Transmitter Holding Register: Register to write the characters to send to the serial line
#define IER 0x01 // Interrupt Enable Register: Register to control the interrupts generated by the UART
#define IIR 0x02 // Interrupt Identification Register: Register that contains several status bits relevant to handle interrupts. It includes also some bits pertaining to the status of FIFO operation
#define FCR 0x02 // FIFO Control Register: Register to control the operation of the FIFO buffers, if available
#define LCR 0x03 // Line Control Register: Register to configure the different asynchronous serial communication parameters
#define MCR 0x04 // Modem Control Register: Register to control various modem control signals
#define LSR 0x05 // Line Status Register: Register that contains several status bits regarding the serial communication
#define MSR 0x06 // Modem Status Register: Register to read the current state of the modem control signals
#define SCRATCHPAD_REG 0x07 // Scratchpad Register: General-purpose register for temporary storage

#define DL_LSB 0x00
#define DL_MSB 0x01

#define LCR_5_BITS_PER_CHAR 0x00
#define LCR_6_BITS_PER_CHAR BIT(0)
#define LCR_7_BITS_PER_CHAR BIT(1)
#define LCR_8_BITS_PER_CHAR (BIT(1) | BIT(0))
#define LCR_TWO_STOP_BITS BIT(2)
#define LCR_ODD_PARITY BIT(3)
#define LCR_EVEN_PARITY (BIT(4) | BIT(3))
#define LCR_PARITY_1 (BIT(5) | BIT(3))
#define LCR_PARITY_0 (BIT(5) | BIT(4) | BIT(3))
#define LCR_ACCESS_DLAB BIT(7)

#define LSR_RECEIVER_DATA BIT(0)
#define LSR_OVERRUN_ERR BIT(1)
#define LSR_PARITY_ERR BIT(2)
#define LSR_FRAMING_ERR BIT(3)
#define LSR_BREAK_INT BIT(4)
#define LSR_THR_EMPTY BIT(5)
#define LSR_TRANSMIT_EMPTY BIT(6)
#define LSR_FIFO_ERR BIT(7)

#define IER_ENABLE_RECEIVED_DATA_INT BIT(0)
#define IER_ENABLE_TRANSMIT_EMPTY_INT BIT(1)
#define IER_ENABLE_RECEIVER_LINE_STATUS_INT BIT(2)
#define IER_ENABLE_MODEM_STATUS_INT BIT(3)

#define IIR_NO_INT BIT(0)
#define IIR_INT_ORIGIN BIT(1) | BIT(2) | BIT(3)
#define IIR_RECEIVED_LINE_STATUS BIT(1) | BIT(2)
#define IIR_RECEIVED_DATA_AVAILABLE BIT(2)
#define IIR_FIFO_CHAR_TIMEOUT BIT(3) | BIT(2) 
#define IIR_TRANSMIT_HOLD_REG_EMPTY BIT(1)
#define IIR_MODEM_STATUS 0x00


#define FCR_ENABLE_FIFO BIT(0)
#define FCR_CLEAR_RECEIVE_FIFO BIT(1)
#define FCR_CLEAR_TRANSMIT_FIFO BIT(2)
#define FCR_ENABLE_64_BYTE_FIFO BIT(5)

#define BIT_RATE_CONST 115200

#define QUEUE_SIZE 30
#endif
